apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-flask-gunicorn-nginx.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
  - name: "18001"
    port: 18001
    targetPort: 80
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
