FROM nginx:1.13.3
ENV LANG=en_US.UTF-8
ENV TZ=Asia/Hong_Kong

RUN rm /etc/nginx/nginx.conf
COPY nginx/nginx.conf /etc/nginx/

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/reverse_proxy.conf /etc/nginx/conf.d
COPY nginx/static /static

