version: '2'
 
services:
  web:
    container_name: fgn-flask
    restart: unless-stopped
    image: cpluk3/fgn-flask:1.0
    expose:
    - "18000"
    command: /usr/local/bin/gunicorn -w 2 -b :18000 run:app
    networks:
    - fgn
 
  nginx:
    container_name: fgn-nginx
    restart: unless-stopped
    image: cpluk3/fgn-nginx:1.0
    ports:
    - "18001:80"
    depends_on:
    - web
    networks:
    - fgn

networks:
    fgn:
        driver: bridge
